name: Generate Search Index

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Search Index
        run: npm run generate-index

      - name: Commit and push search_index.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update search_index.json [auto]"
          file_pattern: search_index.json
